### ISSUE TITLE
SCRIPT5007: Unable to get property 'replace' of undefined or null reference

### ISSUE THREAD

**Issue by edjafarov** [openconf/jschat#29]
IE11:
SCRIPT5007: Unable to get property 'replace' of undefined or null reference
File: app.js, Line: 11081, Column: 1

**Comment by sejoker** [comment]
work in progress

**Comment by sejoker** [comment]
Pull request https://github.com/turbo-react/composer/pull/1 will fix bug in IE. Please merge it and issue new package version.

**Comment by sudodoki** [comment]
:+1: awesome finding.

**Comment by sudodoki** [comment]
@sejoker, since master of composer is updated & it's used in [client's package.json](https://github.com/openconf/jschat/blob/master/client/package.json#L39) it should work now (after cleaning & reinstalling all client dependencies). Can you be so kind and confirm that?

**Comment by sejoker** [comment]
it works in IE, confirmed.

**Comment by sudodoki** [comment]
Thanks!

**Comment by Arunbhaskar** [comment]
@Sejoker, There is no info in this link https://github.com/turbo-react/composer/pull/1 Can you share again...
Thanks in advance:)

**Comment by sejoker** [comment]
@Arunbhaskar I can't help, it is an outdated issue.

**Comment by Arunbhaskar** [comment]
Thx for ur prompt response.

Sent from my Windows Phone,
Arunbhaskar R
