### ISSUE TITLE
[5]make extensive caching of messages [localstorage]

### ISSUE THREAD

**Issue by edjafarov** [openconf/jschat#39]
render only portion of messages. Most of messages should be in localstorage. If LS is drained - upload another portion from server.
keep LS size/cleanup

we need localhost MessagesContainer that keeps last available data
we have RenderedMessagesCollection that is keeping rendered messages
RMC._range [topId, bottomId]
RMC.getTop(number)
RMC.getBottom(number)
RMC.

**Comment by sudodoki** [comment]
https://github.com/openconf/jschat/pull/56. So, I didn't do the `getBottom` and `_range` methods, any particular use cases me might need those? Range selection by date might be useful, maybe, scope out 'get messages for past week' functionality? As for the 

> keep LS size/cleanup

I think best approach might be to have cap collection with some limit set beforehand, like 100/200/500 messages length per room record.
Your thoughts?

**Comment by edjafarov** [comment]
well, I hadn't done any investigation yet but as per http://stackoverflow.com/questions/3027142/calculating-usage-of-localstorage-space we will have exceptions if we will have localstorage overflow thus we need to handle it by ourselves. Maybe have some service that will catch those errors? There might be some solutions already. I guess it should be something like FIFO stack.

**Comment by edjafarov** [comment]
> So, I didn't do the getBottom and _range methods, any particular use cases me might need those? 

I am thinking about search here. For example you will search for some term and you get number of discussion points where you might jump. We will not be able to load everything.
So far though any implmentation is good enough:) We can refactor later.

**Comment by sudodoki** [comment]
1. Will handle the exception & trim current room data then.
2. Will implement #range.
3. More elaborate implementation involves keeping all keys & length of storages records, probably, and trimming the longest first.

**Comment by sudodoki** [comment]
Closed via #56.
