### ISSUE TITLE
Extend standard smileset

### ISSUE THREAD

**Issue by sudodoki** [openconf/jschat#58]
Add :trollface: and :butthurt: smiles.

**Comment by edjafarov** [comment]
:+1: trollface - is a killer feature!

**Comment by edjafarov** [comment]
we need to add http://www.emoji-cheat-sheet.com/

**Comment by edjafarov** [comment]
might be modified https://github.com/hassankhan/emojify.js

**Comment by sudodoki** [comment]
Consider this done for now.
