### ISSUE TITLE
Remove down arrow if there is nothing to expand

### ISSUE THREAD

**Issue by edjafarov** [openconf/jschat#70]
![screen shot 2014-02-07 at 08 22 51](https://f.cloud.github.com/assets/509978/2107141/4f1e407c-8fc0-11e3-9e82-a1d97c3c1e77.png)

remove arrow if there is no that many users yet

**Comment by sudodoki** [comment]
After speaking to you and deciding this should be done using css, that's what I came up with (this is sketch to show the idea): http://codepen.io/sudodoki/pen/KltIe.
Sadly enough, I'm no css guru. 
Drawbacks:
- some values (top for button-wrapper, for example) should be hardcoded,
- no surefire when we're in transition zone (not too that many for button-wrapper to be fully visible (just add 15 values, for example) -> maybe, hover button should be showing at all time just in case?

As a sidenote: using multiellipsis hack (like the canonical one [over here](http://codepen.io/romanrudenko/pen/ymHFh)) couldn't make it work with regular div elements (sorry, lost my codepen with that code) - maybe, somebody else could/would.

**Comment by sudodoki** [comment]
Closed via #84.
