### ISSUE TITLE
Padding disappears on some window width

### ISSUE THREAD

**Issue by edjafarov** [openconf/jschat#73]
![screen shot 2014-02-07 at 08 29 44](https://f.cloud.github.com/assets/509978/2107163/44bc161c-8fc1-11e3-81c0-55d93a6efc87.png)

**Comment by sejoker** [comment]
Can't reproduce in chrome, firefox.

**Comment by sudodoki** [comment]
If I recall correctly, it was fixed via https://github.com/openconf/jschat/commit/bc0840f9a8b57c5264fb445fae04dc889e7d9d4d.

**Comment by sudodoki** [comment]
@sejoker thanks for bringing this up.
