### ISSUE TITLE
Possible functionality duplication

### ISSUE THREAD

**Issue by sudodoki** [openconf/jschat#78]
There's 
https://github.com/openconf/jschat/blob/master/client/reacts/BackboneMixin.js 
and there's
https://github.com/openconf/jschat/blob/master/client/models/ModelMixin.js.
Only place BackboneMixin is used is https://github.com/openconf/jschat/blob/53d55ee3652fd038089ab58f1d93f1360d179258/client/reacts/Contact.js.
Maybe, this was overlooked and should be removed?

**Comment by edjafarov** [comment]
yes it should be removed. These are leftovers:)
