### ISSUE TITLE
devrequest: dev should be able to run tests separately

### ISSUE THREAD

**Issue by edjafarov** [openconf/jschat#8]
mocha can run tests with kind of tags (#tag) we need to leverage this for our server tests

**Comment by sudodoki** [comment]
1. Are you talking about https://github.com/visionmedia/mocha/wiki/Tagging ?
2. What kind of tags are you expecting to see?  'fast'/'slow', 'unit' (in case they're coming)/'integration'?
3. Why not create separate test targets in grunt?

**Comment by edjafarov** [comment]
1) yep, about those tags.
2) any of those as well as custom tags by #featurename
3) dev should be able to mark tests that correspond to feature he is developing.

**Comment by sudodoki** [comment]
Just adding

```
options: {
  grep: '@yourTag'
  reporter: "spec"
}
```

into [gruntfile](https://github.com/openconf/jschat/blob/master/gruntfile.js#L22-L24) will grant you (what a wordplay :wink:) such an ability.

**Comment by edjafarov** [comment]
awesome! that would be even more awesome to have something like 
node runtest.js #mytag
